version: '3.7'

services:
  bde_postgres:
    container_name: bde_postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ../docker:/docker-entrypoint-initdb.d
      - bde_data:/var/lib/postgresql/data
    networks:
      - bde-isima

  bde_pgadmin:
    container_name: bde_pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8008:80
    env_file:
      - .env
    volumes:
      - bde_pgadmin:/var/lib/pgadmin
    networks:
      - bde-isima

volumes:
  bde_data:
  bde_pgadmin:

networks:
  bde-isima:
    external: true
