version: "3.7"

services:
  bde_app:
    container_name: bde_app
    image: node:14
    restart: always
    working_dir: /usr/app
    volumes:
      - ..:/usr/app
    networks:
      - bde-isima-dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://bde_isima:isima@bde_db:5432/bde_db
    entrypoint: sh -c
    command: ./dev/start-dev.sh

  bde_db:
    container_name: bde_db
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=isima
      - POSTGRES_USER=bde_isima
      - POSTGRES_DB=bde_db
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - bde-isima-dev
    ports:
      - "5432:5432"

#  bde_pg4admin:
#    container_name: bde_pg4admin
#    restart: always
#    image: dpage/pgadmin4:latest
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@bde.isima.fr
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    volumes:
#      - ./data/pg4admin:/var/lib/pgadmin
#    ports:
#      - 8080:80
#    networks:
#      - bde-isima-dev

networks:
  bde-isima-dev:
    name: bde-isima-dev
