version: '3.8'

services:
  dev_bde_isima_fr:
    container_name: dev_bde_isima_fr
    image: ghcr.io/bde-isima/bde.isima.fr/refs/pull/22/merge:latest
    restart: unless-stopped
    networks:
      - bde-isima

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/nginx
      - ./confs/nginx.conf:/etc/nginx/nginx.conf:ro
    #  - /etc/ssl/domains/bde.isima.fr:/etc/nginx/certs
    networks:
      - bde-isima
    ports:
      - 443:443
    depends_on:
      - dev_bde_isima_fr

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_MONITOR_ONLY: 'true'
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: __REDACTED__
      WATCHTOWER_NOTIFICATION_EMAIL_TO: __REDACTED__
      # you have to use a network alias here, if you use your own certificate
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 25
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: __REDACTED__
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: __REDACTED__
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    networks:
      - bde-isima
    #depends_on:
    #  - postfix

  #postfix:
  #image: freinet/postfix-relay:latest
  #container_name: postfix
  #restart: unless-stopped
  #expose:
  #- 25
  #environment:
  #MAILNAME: smtp.bde.isima.fr
  #TLS_KEY: '/etc/ssl/domains/bde.isima.fr/bde.isima.fr.key'
  #TLS_CRT: '/etc/ssl/domains/bde.isima.fr/bde.isima.fr.crt'
  #TLS_CA: '/etc/ssl/domains/bde.isima.fr/ca.crt'
  #volumes:
  #  - /etc/ssl/domains/bde.isima.fr/:/etc/ssl/domains/bde.isima.fr/:ro
  #networks:
  #bde-isima:
  # this alias is really important to make your certificate work
  #aliases:
  #- smtp.bde.isima.fr

  db_dev:
    image: postgres:14.1-alpine
    container_name: db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: __REDACTED__
      POSTGRES_USER: __REDACTED__
      POSTGRES_PASSWORD: __REDACTED__
    volumes:
      - bde_data:/var/lib/postgresql/data
    networks:
      - bde-isima

volumes:
  bde_data:

networks:
  bde-isima:
    external: false
