version: '3.7'

services:
  bde_watchtower:
    container_name: bde_watchtower
    image: containrrr/watchtower:latest
    restart: always
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .docker/config.json:/config.json
    command: --interval 60

  bde_vault:
    container_name: bde_vault
    image: vaultwarden/server:latest
    restart: always
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      ADMIN_TOKEN: REDACTED
      DOMAIN: "https://bde.isima.fr/vault"
    volumes:
      - ../webvault:/data
    networks:
      - bde_isima_net

  bde_nginx:
    container_name: bde_nginx
    image: nginx:1.23-alpine
    restart: always
    volumes:
      - ./servers/logs:/var/log/nginx
      - ./servers/conf:/etc/nginx/conf.d
      - ./servers/ssl:/etc/nginx/certs
    networks:
      - bde_isima_net
    depends_on:
      - bde_app
      - bde_app_dev
      - bde_pgadmin
    ports:
      - 80:80
      - 443:443

  bde_app:
    container_name: bde_app
    image: ghcr.io/bde-isima/bde.isima.fr/production:latest
    restart: always
    networks:
      - bde_isima_net
    depends_on:
      - bde_postgres

  bde_app_dev:
    container_name: bde_app_dev
    image: ghcr.io/bde-isima/bde.isima.fr/staging:latest
    restart: always
    networks:
      - bde_isima_net
    depends_on:
      - bde_postgres

  bde_postgres:
    container_name: bde_postgres
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./.env
        target: /docker-entrypoint-initdb.d/.env
      - ./databases:/docker-entrypoint-initdb.d
      - bde_data:/var/lib/postgresql/data
    networks:
      - bde_isima_net

  bde_pgadmin:
    container_name: bde_pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    volumes:
      - bde_pgadmin:/var/lib/pgadmin
    networks:
      - bde_isima_net
    depends_on:
      - bde_postgres

volumes:
  bde_data:
  bde_pgadmin:

networks:
  bde_isima_net:
    driver: bridge
