name: Database migrations

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  buildAndDeploy:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: 16
        run: yarn install --progress=false

      - name: Run migrations
        run: yarn migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
