name: Database migrations

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  migrations:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: jq -r .dependencies["prisma"]

      - name: Run migrations
        run: yarn global add prisma@${{ steps.version.outputs.value }} && yarn migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
